version: "3"
services:
  app-auth-server:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: poetry run python3 manage.py runserver 0.0.0.0:8024
    ports:
      - "8024:8024"
    networks:
      - auth-network
      - default
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql:8
    ports:
      - "3308:3308"
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_USER=ratchaphon1412
      - MYSQL_PASSWORD=Nueng1412
      - MYSQL_ROOT_PASSWORD=Nueng1412
      - MYSQL_TCP_PORT=3308
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - auth-network
  vault:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=Ratchaphon1412
    volumes:
      - ./vault:/vault/file
    networks:
      - auth-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app-auth-server
    networks:
      - auth-network
networks:
  auth-network:
    driver: bridge
