version: "3"
services:
  app-auth-server:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: poetry run python3 manage.py runserver 0.0.0.0:8024
    ports:
      - "8024:8024"
    networks:
      - auth-network
      - default
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "pixelmanauth"
      MYSQL_USER: "Ratchaphon1412"
      MYSQL_PASSWORD: "Nueng111"
      MYSQL_ROOT_PASSWORD: "Nueng111"
      MYSQL_TCP_PORT: 3306
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - auth-network
  vault:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - ./vault:/vault/file:rw
    networks:
      - auth-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app-auth-server
    networks:
      - auth-network
networks:
  auth-network:
    driver: bridge
